version: '3.7'

services:

  sample:
    image: reactrapp
    container_name: reactrappcontainer
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true